name: publish
on: [push]
jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build docker image for hw1_not_ready (without giving it the optional argument IS_READY=true)
      run: |
        docker build . --tag ghcr.io/ah-aydin/hw1_not_ready:latest
        docker push ghcr.io/ah-aydin/hw1_not_ready:latest